

GET http://localhost:3000/api/people



### crear
POST http://localhost:3000/api/people
Content-Type: application/json

{
    "nombre":"Emilio", 
    "apellido":"valle", 
    "telefono":"89854578", 
    "tipo":"cliente"
}


### Actualizar
PUT http://localhost:3000/api/people/2
Content-Type: application/json

{
    "imagenUrl":"images.unsplash.com/photo-1492681290082-e932832941e6"
}

### obtener uno
GET http://localhost:3000/api/people/2

### eliminar
DELETE http://localhost:3000/api/people/2



